### ISSUE TITLE
Allow package to work if otp is installed on system

### ISSUE THREAD

**Issue by Robinlovelace** [ropensci/opentripplanner#10]
As per the docs, this would involve supporting otp built from source: http://docs.opentripplanner.org/en/latest/Getting-OTP/#building-from-source

E.g. as demonstrated below:

``` r
system2("otp", stdout = T)
#> Warning in system2("otp", stdout = T): running command ''otp'' had status
#> 255
#> [1] "02:07:25.478 INFO (OTPMain.java:68) Nothing to do. Use --help to see available tasks."
#> attr(,"status")
#> [1] 255
```

<sup>Created on 2019-04-02 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by layik** [comment]
Avoid build from source is my initial and probably not changing stance for this package.

Download from https://repo1.maven.org/maven2/org/opentripplanner/otp/1.1.0/otp-1.1.0-shaded.jar and live happily ever after. If statement to be 100% safe, if not available or removed for security etc, then stop that particular `setup` function.

I think there is already enough in the package, I think! But ultimately it is the user's responsibility.

**Comment by Robinlovelace** [comment]
I meant the package should work if you have installed `OTP` on your system, not that the package should install the package from source for you. I just installed from source to get around the issue of having multiple versions of Java and it works great. And it makes the API more concise:

```
otp --help
```

vs

```
java ~/programs/OTP/shadad.jar --help
```

for example.

**Comment by Robinlovelace** [comment]
The other advantage of OTP installed this way this is that it keeps the main version of `java` on your system while ensuring that the version of `java` OTP needs is used for calling the `jar` file.

**Comment by layik** [comment]
“
This build process should produce a JAR file called otp-x.y.z-shaded.jar in the target/ directory which contains all the compiled OTP classes and their dependencies (the external libraries they use). The shell script called 'otp' in the root of the cloned repository will start the main class of that JAR file under a Java virtual machine, so after the Maven build completes you should be able to run ./otp --help and see an OTP help message including command line options. Due to the way Maven works, this script is not executable by default, so you will need to do chmod u+x ./otp before you run it to mark it as executable.

“
Windows will not be happy with a shell script.

**Comment by layik** [comment]
Importantly I think the 1.8 is just the minimum version than the required one.

**Comment by Robinlovelace** [comment]
>  Windows will not be happy with a shell script.

That may be so, but whether or not `opentripplanner` supports users who have installed OTP on their system has no impact on Windows users in this PR #11 

Windows users are not affected by people who install it on their system, e.g. with this: https://github.com/ITSLeeds/opentripplanner/pull/11/files#diff-93d3b13dfc8970e3781563bf840882bcR101

The `system()` calls required are the same, albeit slightly simpler: https://github.com/ITSLeeds/opentripplanner/pull/11/files#diff-3ca3b41aa0b4803f8220af78a5d0b854R59

**Comment by Robinlovelace** [comment]
Example of simpler calls to OTP, without OTP installed on the system:

``` r
system("java -Xmx6G -Xverify:none -jar ~/programs/OpenTripPlanner/target/otp-1.4.0-SNAPSHOT-shaded.jar \"--version\"", 
    intern = T)
#> [1] "version: 1.4.0-SNAPSHOT"                         
#> [2] "major: 1"                                        
#> [3] "minor: 4"                                        
#> [4] "patch: 0"                                        
#> [5] "qualifier: SNAPSHOT"                             
#> [6] "commit: 135671945eeab2a8fd1cd285fbda8349540cdc34"
#> [7] ""
```

<sup>Created on 2019-04-02 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Or 

``` r
system("otp --version", intern = T)
#> [1] "version: 1.4.0-SNAPSHOT"                         
#> [2] "major: 1"                                        
#> [3] "minor: 4"                                        
#> [4] "patch: 0"                                        
#> [5] "qualifier: SNAPSHOT"                             
#> [6] "commit: 135671945eeab2a8fd1cd285fbda8349540cdc34"
#> [7] ""
```

<sup>Created on 2019-04-02 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

I know which one I'd rather use if I were developing OTP applications. Plus allowing people to use compiled versions of OTP encourages development because the effects of changing the source code can be seen in updated binaries - giving users more control.

**Comment by layik** [comment]
Alright, I am not going to change my mind: 1. build from source is wrong IMHO, 2. introducing a bash script is against Java's jar. Even if that is coming from Oracle themselves unless I know less Java than R which is not the case :)

I should let Robin do this the way he wants to. I should be on holiday anyways :)

**Comment by Robinlovelace** [comment]
Open minded about this, just an idea, and definitely willing to change my mind so have removed that from PR. Can always re-open this issue if there's demand down the line but happy to defer to your judgement @layik that it's a bad idea. One to discuss/test/minihack at some point.
