### ISSUE TITLE
Directory error on Mac prevents graph build

### ISSUE THREAD

**Issue by jamiedtor** [ropensci/opentripplanner#100]
**Describe the bug**
When trying to run the demo from the getting started vignette, the graph build fails with an error indicating that the "default" directory "is not a directory."  I've verified that the directory does exist and all of the demo files are properly downloaded.

> > log <- otp_build_graph(otp = path_otp, dir = "~/Documents/OTP")
> You have the correct version of Java for OTP 1.x
> 2023-01-15 14:24:42 Basic checks completed, building graph, this may take a few minutes
> The graph will be saved to ~/Documents/OTP/graphs/default
>  
> Error: OTP did not report a sucessfull graph build
> Last reported steps:
> OpenTripPlanner 1.5.0 bbf62e2902d0f36046c4421d551d216cc6f48fc514:24:42.321 ERROR (OTPMain.java:63) Parameter error: --build: '~/Documents/OTP/graphs/default' is not a directory.
> OpenTripPlanner 1.5.0 bbf62e2902d0f36046c4421d551d216cc6f48fc5
> 14:24:42.321 ERROR (OTPMain.java:63) Parameter error: --build: '~/Documents/OTP/graphs/default' is not a directory.
> 
> OpenTripPlanner 1.5.0 bbf62e2902d0f36046c4421d551d216cc6f48fc5
> 14:24:42.321 ERROR (OTPMain.java:63) Parameter error: --build: '~/Documents/OTP/graphs/default' is not a directory.
> Warning message:
> In system(text, intern = TRUE) :
>   running command 'java -Xmx2048M -d64 -jar "/Library/Frameworks/R.framework/Versions/4.2/Resources/library/opentripplanner/jar/otp-1.5.0-shaded.jar" --build "~/Documents/OTP/graphs/default"' had status 1
> > 

**To Reproduce**
```
library(opentripplanner)
# Path to a folder containing the OTP.jar file, change to where you saved the file.
path_data <- file.path("~/Documents", "OTP")
dir.create(path_data)
path_otp <- otp_dl_jar()
otp_dl_demo(path_data)
# Build Graph and start OTP
log1 <- otp_build_graph(otp = path_otp, dir = path_data)
log2 <- otp_setup(otp = path_otp, dir = path_data)
otpcon <- otp_connect(timezone = "Europe/London")
```

**Expected behavior**
I expected the graph to build in that location. 

**Screenshots**

**System**
> sessionInfo()
R version 4.2.1 (2022-06-23)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Ventura 13.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

locale:
[1] en_CA.UTF-8/en_CA.UTF-8/en_CA.UTF-8/C/en_CA.UTF-8/en_CA.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] opentripplanner_0.5

loaded via a namespace (and not attached):
[1] compiler_4.2.1  backports_1.4.1 tools_4.2.1     checkmate_2.1.0

**Additional context**

**Comment by mem48** [comment]
Have you tried not using the relative file path `~`

**Comment by jamiedtor** [comment]
That solved it.  file.path("Documents", "OTP") was works.
