### ISSUE TITLE
Turn restrictions added to local .pbf not observed in routing with local instance

### ISSUE THREAD

**Issue by jamiedtor** [ropensci/opentripplanner#101]
We've been attempting to use opentripplanner to test the impacts of various street-work scenarios, including inserting or removing links/ways and imposing turn restrictions.  As a trial, we've attempted to edit the demo Isle of Wight .pbf using JOSM and its plugins pbf and turnrestrictions before creating a new graph and testing with Grizzly.

The removal or addition of new ways are accounted for in routing; new turn restrictions are not.  You can see in this first image, the route between the test origin and destination makes use of "Testing Road" via a left turn from Steynes.  "Testing Road" is a completely new way and the routing engine uses it.

![Screenshot 2023-01-15 183824](https://user-images.githubusercontent.com/90428083/212574090-42d99384-7704-41b7-ab0e-3f6488410773.png)

In the second image, you can see that with "Testing Road" removed from the .pbf (and the graph is rebuilt), a different driving route is selected.

![no_testing](https://user-images.githubusercontent.com/90428083/212574386-2e30f5da-a48d-4722-bee6-25888f501098.png)

The engine appears, however, to ignore newly created turn restrictions. In this third image, you can see two turn restrictions that should make it impossible to complete the route shown in the fourth image. 

![Screenshot 2023-01-15 185631](https://user-images.githubusercontent.com/90428083/212574494-a9bbfc39-18c5-4326-90c3-20112b683542.png)

Neither the left turn from Steyne to "Testing Road," nor the right turn onto Swains should be permitted.

![Screenshot 2023-01-15 183824](https://user-images.githubusercontent.com/90428083/212574553-7d1022ee-2f39-440c-83ac-d8ad0cb89774.png)

The code I used is directly drawn from the "getting started" vignette. It appears to work in all other respects. 

```
library(opentripplanner)

path_data <- file.path("C:/Users/Public", "OTP")

dir.create(path_data) 

path_otp <- otp_dl_jar()

otp_dl_demo(path_data)

log1 <- otp_build_graph(otp = path_otp, dir = path_data, memory = 10240) 

log2 <- otp_setup(otp = path_otp, dir = path_data, port = 8801, securePort = 8802)

otp_stop()

#start <- (50.68554, -1.08475)

#end <- (50.69033, -1.07949)
```

Session Info:
R version 4.2.2 (2022-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] LC_COLLATE=English_Canada.utf8  LC_CTYPE=English_Canada.utf8    LC_MONETARY=English_Canada.utf8
[4] LC_NUMERIC=C                    LC_TIME=English_Canada.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] opentripplanner_0.5

loaded via a namespace (and not attached):
[1] compiler_4.2.2     rjson_0.2.21       backports_1.4.1    RcppSimdJson_0.1.8 tools_4.2.2       
[6] curl_5.0.0         Rcpp_1.0.9         checkmate_2.1.0

**Comment by mem48** [comment]
This is a problem with OpenTripPlanner, not the R package please open an issue at https://github.com/opentripplanner/OpenTripPlanner
