### ISSUE TITLE
Error when no results returned

### ISSUE THREAD

**Issue by mem48** [ropensci/opentripplanner#105]
```
> routes_test = otp_plan(otpcon = otpcon,
+                             fromPlace = c(-1.55555, 53.81005), #Lng/Lat
+                             toPlace = c(-1.54710, 53.79519),
+                             mode = c("CAR_PARK","BICYCLE")) 
Error in UseMethod("st_as_sfc") :                                                                                             
  no applicable method for 'st_as_sfc' applied to an object of class "NULL"


```

**Comment by vbrulli** [comment]
Hi ! I tried to use the otp_plan in batch mode (with a list of destination coordinates). Some of them are in the middle of nowhere so with no itinerary possible. When I run it with get_geometry = TRUE, i get the same error as above. When get_geometry = FALSE, i get the following error : 
2023-07-02 11:16:10 processing results
Error in `[.data.frame`(results_routes, c("fromPlace", "toPlace", colnms)) : 
  undefined columns selected
I use the script in this way: 
itin_temp2 <- otp_plan(
  otpcon = otpcon2,
  fromPlace = origin,
  toPlace = points_coord,
  date_time = as.POSIXct(strptime("2023-05-08 13:30", "%Y-%m-%d %H:%M")),
  mode = "TRANSIT",
  arriveBy = FALSE,
  get_geometry = FALSE
)

**Comment by mem48** [comment]
Thanks for the bug report, can you confirm the version of the package you are using, and if you have tried using the github version?
