### ISSUE TITLE
[BUG] otp_make_config("otp") does not list 'otp' options - produces same output as otp_make_config("router")

### ISSUE THREAD

**Issue by oweno-tfwm** [ropensci/opentripplanner#107]
**Describe the bug**
otp_make_config("otp") does not list 'otp' options - produces same output as otp_make_config("router")

reproduction:

```
if(!require('opentripplanner')) {
  install.packages('opentripplanner')
  library('opentripplanner')
}

if(!require('jsonlite')) {
  install.packages('jsonlite')
  library('jsonlite')
}
{
  print("=====")
  print("opt.json")
  print(toJSON(otp_make_config("otp"), pretty=TRUE, auto_unbox = TRUE))  
  print("=====")
  print("router.json")
  print(toJSON(otp_make_config("router"), pretty=TRUE, auto_unbox = TRUE))  
  print("=====")
  print("build.json")
  print(toJSON(otp_make_config("build"), pretty=TRUE, auto_unbox = TRUE))  
  print("======")
}

```
**Expected behavior**
should list the config options detailed here https://docs.opentripplanner.org/en/v2.3.0/Configuration/

**Screenshots**

**System**
> sessionInfo()
R version 4.2.2 (2022-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.utf8  LC_CTYPE=English_United Kingdom.utf8   
[3] LC_MONETARY=English_United Kingdom.utf8 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] jsonlite_1.8.7        opentripplanner_0.5.1

loaded via a namespace (and not attached):
[1] compiler_4.2.2  backports_1.4.1 tools_4.2.2     checkmate_2.2.0 Please paste `sessionInfo()` here:

**Additional context**

**Comment by mem48** [comment]
If you want to use otp v2.3 then you need to do `otp_make_config("otp", version = 2)`

**Comment by mem48** [comment]
The `opentripplanner` package is still mostly focused on OTP v1.5 because of the additional analysis features that are in v1.5 and were removed for v2.

**Comment by mem48** [comment]
See https://docs.ropensci.org/opentripplanner/articles/OTPv2.html

> Note OpenTripPlanner is undergoing some significant changes at the moment with features being added and removed. To avoid constant updates to the R package we are currently targeting support at v1.5 and v2.2. Other versions may work but are not officially supported.
