### ISSUE TITLE
[BUG] Set date and time for queries

### ISSUE THREAD

**Issue by jc-ulles** [ropensci/opentripplanner#111]
Hello,
When I launch an OTP session, the afternoon times are systematically converted to the morning. I've tried to change the settings but without success. I use OTP from France.
The code is as follows:

otp_setup(otp = path_otp, dir = path_data)
myOtpcon <- otp_connect(timezone = "Europe/Paris")

route <- otp_plan(otpcon=myOtpcon, 
               fromPlace = c(3.92320, 43.59586), 
               toPlace = c(3.91605, 43.60383),
               mode = c("WALK", "TRANSIT"),
               date_time = as.POSIXct("2023-10-23 21:00:00"))

The result in "startTime" and "endTime" is "2023-10-23 09:08:08" and "2023-10-23 09:18:15".
This result is good if I had indicated "2023-10-23 09:00:00" but not for "2023-10-23 21:00:00" as I would like.

I tried, without success, this :
date_time = as.POSIXct("2023-10-23 21:00", format = "%Y-%m-%d %H:%M")

I guess there's a problem with the time conversion, but I haven't been able to solve it.
Is there any way to request the afternoon?
I got the same issue with otp_isochrone().

I'm using the last version (0.5.1) and this [GTFS](https://transport.data.gouv.fr/datasets/offre-de-transport-de-montpellier-mediterranee-metropole-tam-gtfs).

Many thanks!

**Comment by jc-ulles** [comment]
I found the solution in the #85, I changed my R settings with:
Sys.setlocale("LC_TIME","en_US.UTF-8")

**Comment by mem48** [comment]
I suggest using the package `lubridate` when setting `date_time` as these kinds of timezone problems are common in R
