### ISSUE TITLE
otp_isochrone output

### ISSUE THREAD

**Issue by jameswoodgeog** [ropensci/opentripplanner#118]
**Is your feature request related to a problem? Please describe.**
When calculating the isochrones from an sf object, the process produces a new object, and there is now way to tell which line of the output relates to the input file.

**Describe the solution you'd like**
It would be great to have the option within the parameters to select a column that one wishes to use as a reference between original and output. The default could be the index, but if required, it could be changed.

**Describe alternatives you've considered**
I have not found an alternative. I am trusting that the output is in the same sequential order as the input (which could prove dangerous for obvious reasons)

**Additional context**

**Comment by mem48** [comment]
Do you mean `fromID`? See https://docs.ropensci.org/opentripplanner/reference/otp_isochrone.html
