### ISSUE TITLE
test on public api

### ISSUE THREAD

**Issue by mem48** [ropensci/opentripplanner#13]

**Comment by mem48** [comment]
Digitransit have change their API, this requires a significant rewrite of the package or finding a new API to test against.

**Comment by mem48** [comment]
https://digitransit.fi/en/developers/apis/1-routing-api/

**Comment by mem48** [comment]
https://developer.trimet.org/ requires API key

https://www.mbta.com/developers/v3-api  no key ??

**Comment by Robinlovelace** [comment]
Note: you can test APIs on travis with something like:

```r
if(nchar(Sys.getenv("TRIMET)) > 0 ) {
  # do tests ...
}
```

I don't think this is a priority, getting it on CRAN after 6th Jan when they're all back from holiday should be priority I think.

**Comment by mem48** [comment]
I agree, my problem is finding a free api to test against. Most otp sites don't offer an API.

**Comment by mem48** [comment]
Also the package does not currently support api keys, so some rewriting would be required

**Comment by mem48** [comment]
Trimet uses differnt url strucutre in api and is not compatiable with the package :(

**Comment by mem48** [comment]
Closing until testible service exists
