### ISSUE TITLE
Batch Isochone & Geocoding

### ISSUE THREAD

**Issue by mem48** [ropensci/opentripplanner#20]
Support batch isochrone and geocoding

**Comment by orlandombaa** [comment]
Hello 

I have a question.  So currently is not possible  to make a request of a isochrones using a matrix? I mean make many isochrones from many places? 

I want to use this to measure the spatial coverage of all the stops of the network. 

thank you

**Comment by mem48** [comment]
Hi, yes at the moment you can't input a matrix, you would have to write your own loop. Its on the to do list of features to add. 

Writing a simple loop is easy, but providing the full multicore  batch processing that is in otp_plan() is more complex. Whichis why it has not been done yet.

**Comment by mem48** [comment]
@orlandoandradeb I've made a branch with batch isochrone support in the similar style to `otp_plan()` at https://github.com/ropensci/opentripplanner/tree/batch-isochrone let me know if it works for you.

**Comment by mem48** [comment]
Batch Isochrone is done and on CRAN. Not going to do geocoding for now as no clear use case.

**Comment by Robinlovelace** [comment]
Great work @mem48, productive social distancing!
