### ISSUE TITLE
OTP / Java set up issue on Windows

### ISSUE THREAD

**Issue by kimnewzealand** [ropensci/opentripplanner#28]
Hi there opentripplanner team

I am going through the installation and set up for the package review. I have updated Java to version 8 and installed and attached the R package opentripplanner, as per the vignettes. I am raising this is as an issue as I am unable to progress on the review at this point.

I initially suspected there an issue with the OTP connection as the check for OTP did not return TRUE. (I did not change the .Renviron file at that point, as suggested in the vignette, see next).
` Sys.getenv("I_have_OTP")`
>[1] ""

The build of a graph object also returned an error message:

`log <- otp_build_graph(otp = path_otp, dir = path_data) `
> Basic checks completed, building graph, this may take a few minutes
> Failed to build graph with message:
> Error occurred during initialization of VMCould not reserve enough space for 2097152KB object heap
> Warning message:
> In system(text, intern = TRUE) :
> running command 'java -Xmx2G -jar > >"C:\Users\Home\AppData\Local\Temp\RtmpoNFxd9/OTP/otp.jar" --build >"C:\Users\Home\AppData\Local\Temp\RtmpoNFxd9/OTP/graphs/default"' had status 1

I did some Googling and tried this fix on the environment variables in the control panel:
System Variables->New:
Variable name: _JAVA_OPTIONS
Variable value: -Xmx2G

Edit Environment Variable path:
Variable name: Path
Variable value: ;C:\Program Files\Java\jre6\bin;F:\JDK\bin;

I now see a successful OTP connection,

` Sys.getenv("I_have_OTP")`
> [1] "TRUE"

I then retried the graph object  and perhaps the new variables are good as it looks like it has gone past the initialisation,  but there appears to be a Java version issue now. ? I am not familiar with Java so I was wondering if you could advise on what to try next?

> # Run the OTP and Build a graph object
` log <- otp_build_graph(otp = path_otp, dir = path_data) `
> Error in otp_checks(otp = otp, dir = dir, router = router, graph = FALSE) : 
  
> In addition: Warning messages:
>1: In system2("java", "-version", stdout = TRUE, stderr = TRUE) :
>  running command '"java" -version' had status 1
>2: In otp_checks(otp = otp, dir = dir, router = router, graph = FALSE) :
>  NAs introduced by coercion
>3: In otp_checks(otp = otp, dir = dir, router = router, graph = FALSE) :
 

Also see below the session information:

` sessionInfo()`
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_New Zealand.1252  LC_CTYPE=English_New Zealand.1252   
[3] LC_MONETARY=English_New Zealand.1252 LC_NUMERIC=C                        
[5] LC_TIME=English_New Zealand.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] opentripplanner_0.1.0.0000

loaded via a namespace (and not attached):
 [1] compiler_3.5.1   backports_1.1.4  clisymbols_1.2.0 tools_3.5.1      fs_1.2.6        
 [6] glue_1.3.1       rstudioapi_0.9.0 yaml_2.2.0       crayon_1.3.4     Rcpp_1.0.1      
[11] usethis_1.5.0    checkmate_1.9.3  rlang_0.3.4

**Comment by mem48** [comment]
Thanks for the detailed responce I'll try to reprodduce the issue, and get back to you asap

**Comment by mem48** [comment]
A few first thoughts, the I_have_OTP is not necessary to use the package only for running the automated tests. The first thing that otp_build_graph does is run the internal function otp_checks. It might be useful to run this via opentripplanner:::otp_checks() to see if a more useful error message is produced. But it seems that you have several distinct problems.

1. On your first attempt Java tried to allocate  2097152KB of memory and failed (about 2 GB) which is the default. Perhaps you are running on a laptop with low memory? You could try memory = 1 in otp_build_graph. The demo data should build in 1 GB.

2. You make some changes to your path, I'm not quite sure what you did,  do you have a link to the instructions you followed? But it now seems that R is unable to check the Java version which would suggest a problem with your java installation. You can check this manually in Comand Prompt with java -version

**Comment by kimnewzealand** [comment]
thanks @mem48 

I am trying on another laptop now so I will update thread soon

**Comment by kimnewzealand** [comment]
As an update, I have uninstalled and reinstalled Java version 8 on my machine and installed the package on another laptop with more memory.

I will ignore Sys.getenv("I_have_OTP") for now as you suggest.

I tried to run this command and received an error:
` opentripplanner:::otp_checks()`
> Error in opentripplanner:::otp_checks() : 
>  Assertion on 'dir' failed: No directory provided.

1. Despite the error with `opentripplanner:::otp_checks()`,  I had success in building the graph by adding memory =1 on both laptops, see below message:

> # Run the OTP and Build a graph object
` log <- otp_build_graph(otp = path_otp, dir = path_data, memory = 1) `
> Basic checks completed, building graph, this may take a few minutes
> Graph built

2. I removed the path and variables as this didn't appear to be necessary on the other laptop. I suspect that the Java upgrade didn't work the first time round. Potentially Java needed a full uninstall first.

`C:\Users\Home>java -version`
> java version "1.8.0_211"
> Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
> Java HotSpot(TM) Client VM (build 25.211-b12, mixed mode, sharing)

Any further thoughts? Else this can probably be closed

**Comment by mem48** [comment]
Seems like its fixed, the otp_ckecks requires several arguments to work, sorry I did not make that clear before. So the error is expected. I think for now I will update the vignettes to mention memory requirements and perhaps some more tips on installing Java.
