### ISSUE TITLE
remote install throw an error

### ISSUE THREAD

**Issue by nujcharee** [ropensci/opentripplanner#31]
When following your readme file bring to remote install the package I received an error message below

Error in curl::curl_fetch_memory(url, handle = h) : 
  Timeout was reached: Operation timed out after 10004 milliseconds with 0 out of 0 bytes received

**Comment by mem48** [comment]
Hi @nujcharee can you post a reproducible example with details about your system?

**Comment by nujcharee** [comment]
Hi there it looks to be ok now that I tried again today. Thank you.
