### ISSUE TITLE
N x N matrix 

### ISSUE THREAD

**Issue by orlandombaa** [ropensci/opentripplanner#33]
Hello 

I'm trying to get the trip data from a matrix of N x N origins. I have my area of service divided into a set of polygons, each with a centroid. What I want to generate is the grade of accessibility which measures the time of each centroid to the rest of the centroids (including itself which is = 0) and the Deuter index which is related to distances. 

I have been reading the advanced documentation  but I get still an error. The ways I have been trying to do are: 

`routes <- otp_plan(otpcon = otpcon,
                   fromPlace = centroides,
                   toPlace = centroides, mode = ("CAR"),ncores = 5)`

centroids is a SF object with the coordinates in its geometry so is a valid data frame. The error that I get is the following (error 1):
![error 1](https://user-images.githubusercontent.com/48104481/66082726-09315480-e56b-11e9-855e-38685e19200e.PNG)

All the points are within a valid area, I have measured the time from a single point to the all set of centroids and it runs well.

The other way I want to do it is following more closer the sintaxis of the tutorial which is : 

`toPlace   = centroides[rep(1, nrow(centroides), times = nrow(centroides)),]
fromPlace = centroides[rep(1, nrow(centroides), each  = nrow(centroides)),] 
`

This generated 2 variables (from places which will have rows of N^N   and to Place which is going to have N rows) and I use them in the function `otp_plan` like I do it in a one to one origin and destination:

`OD_Matrix <- otp_plan(otpcon = otpcon,     
                      fromPlace = fromPlace,
                      toPlace   = toPlace,
                      mode=("CAR"), get_geometry = FALSE, ncores = 5)`

This gives me the following error:

![error 2](https://user-images.githubusercontent.com/48104481/66083034-c328c080-e56b-11e9-9bb9-60e520ad9007.PNG)

In this case, I don't understand why is a problem that the number of rows in origins and the number of rows in the destination is a problem if previously I have used from a single origin to many destinations without a problem. 

I hope someone can help me. 

Best regards, 
Orlando

**Comment by mem48** [comment]
Hi Orlando,

First, if you do this:

`routes <- otp_plan(otpcon = otpcon, fromPlace = centroides, toPlace = centroides, mode = ("CAR"),ncores = 5)`

Then you are routing from A to A, B to B, C to C etc. This is why you get the error "Origin is within a trivial distance of the destiantion"

The second version, based on the vignette should work. Can you do a few checks from me?

```
toPlace = centroides[rep(1, nrow(centroides), times = nrow(centroides)),] 
fromPlace = centroides[rep(1, nrow(centroides), each = nrow(centroides)),] 
nrow(toPlace)
nrow(fromPlace)
nrow(centroides)
summary(toPlace)
summary(fromPlace)
```

**Comment by mem48** [comment]
Hi again,

I've spotted a bug in the vignette code. I've updated the vignette that should fix the problem.

**Comment by mem48** [comment]
```
toPlace   = lsoa[rep(seq(1, nrow(lsoa)), times = nrow(lsoa)),]
fromPlace = lsoa[rep(seq(1, nrow(lsoa)), each  = nrow(lsoa)),]
```

Is the changed code

**Comment by orlandombaa** [comment]
Hello, @mem48  I just run the new code and it runs very well. 
Thank you!
