### ISSUE TITLE
Meet ropensci standards

### ISSUE THREAD

**Issue by mem48** [ropensci/opentripplanner#4]
https://ropensci.github.io/dev_guide/building.html#building

- [x] 1.1.1 Naming your package

- [x] 1.1.2 Creating metadata for your package

- [x] 1.2 Platforms

- [x] 1.4 Function and argument naming

- [x] 1.4.1 Console messages

- [x] 1.5 Code Style

- [x] 1.6 README

- [x] 1.7 Documentation

- [x] 1.8 Documentation website

- [x] 1.8.1 Grouping functions in the reference

- [x] 1.8.2 Automatic deployment of the documentation website

- [x] 1.8.3 Branding of authors

- [x] 1.9 Authorship

- [x] 1.10 Testing

- [x] 1.11 Examples

- [x] 1.12 Package dependencies

- [x] 1.13 Recommended scaffolding

- [x] 1.14 Miscellaneous CRAN gotchas

- [x] 1.15 Further guidance

- [x] 2.3.1 Travis CI (Linux and Mac OSX)

- [x] 2.3.2 AppVeyor CI (Windows)

- [x] 2.4 Test coverage

- [x] 3.1 Misc

- [x] JOSS Paper

- [x] 7.1.1 General guidelines

**Comment by layik** [comment]
I could tick off platforms and AppVeyor. 67% coverage is good for tests too.

**Comment by mem48** [comment]
@Robinlovelace It's all down to you now 😆

**Comment by Robinlovelace** [comment]
Testing on Linux.

**Comment by mem48** [comment]
Done and submitted to ROpenSci
