### ISSUE TITLE
Question about test failure

### ISSUE THREAD

**Issue by vsoch** [ropensci/opentripplanner#43]
heyo! I'm new to this package and general R testing, so please excuse that off the bat. I'm running tests for your package, and I'm hitting this error:
```
* checking tests ... ERROR
  Running ‘testthat.R’
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  
  ── 1. Error: (unknown) (@test_04_with_public_API.R#4)  ─────────────────────────
  Router https://api.digitransit.fi:443/routing/v1/routers/hsl does not exist. Error code 404
  Backtrace:
   1. opentripplanner::otp_connect(url = "https://api.digitransit.fi:443/routing/v1/routers/hsl")
  
  ══ testthat results  ═══════════════════════════════════════════════════════════
  [ OK: 66 | SKIPPED: 19 | WARNINGS: 5 | FAILED: 1 ]
  1. Error: (unknown) (@test_04_with_public_API.R#4) 
  
  Error: testthat unit tests failed
  In addition: Warning messages:
  1: closing unused connection 5 (<-localhost:11339) 
  2: closing unused connection 4 (<-localhost:11339) 
  Execution halted
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in ‘inst/doc’ ... OK
* checking running R code from vignettes ... NONE
  ‘advanced_features.Rmd’using ‘UTF-8’... OK
  ‘known_issues.Rmd’using ‘UTF-8’... OK
  ‘opentripplanner.Rmd’using ‘UTF-8’... OK
  ‘prerequisites.Rmd’using ‘UTF-8’... OK
* checking re-building of vignette outputs ... OK
* DONE
Status: 1 ERROR, 1 NOTE
```
It looks like an issue with a router / endpoint not working - have you seen this before? I'm trying to run the tests from GitHub Actions, if that helps. Thank you!

**Comment by mem48** [comment]
Hi @vsoch it might be a port issue, or perhaps the servers where down when you ran the test. The tests have been designed for travis, to ensure that the code coverage requirements are met. If you want to test the package fully you need to test it locally with Java 8 installed and with the I_have_OTP = TRUE variable in your Renvirion file. Full explanation in the readme.

**Comment by mem48** [comment]
Is there something specific your trying to do with the tests?

**Comment by vsoch** [comment]
Yes, I'm trying to build a general CI that can test any package, so having a custom set of requirements proves to be highly challenging. I'm doing:

```bash
Rscript -e "rcmdcheck::rcmdcheck(args = '${{ matrix.config.args }}', error_on = 'warning', check_dir = '../check')"
```

**Comment by vsoch** [comment]
In case you can see, the current version of the test matrix is being [run here](https://github.com/r-universe/vsoch/pull/13) and a specific failure (for linux, I'm starting with linux since it will be easiest) is [here](https://github.com/r-universe/vsoch/pull/13/checks?check_run_id=359514693). The error message is from the artifact (and I posted it in the issue) if you want to see it in full.

**Comment by mem48** [comment]
It seems that digitransit have changed their API and this is causing the tests to fail, so for now I have disabled the tests that use digitransit. That should fix your problem.

**Comment by vsoch** [comment]
Great thank you! Testing now!

**Comment by vsoch** [comment]
Perfecto! The tests are passing 

![image](https://user-images.githubusercontent.com/814322/71375582-02b7e500-257c-11ea-9cde-1e02a944af73.png)

Now I can move forward and work on the staged builds. Thanks so much for your prompt response!
