### ISSUE TITLE
Support API Keys

### ISSUE THREAD

**Issue by mem48** [ropensci/opentripplanner#45]
For remote servers it would be good to support API keys and login requirments, need an example to build around so waiting for someone in need.

**Comment by Robinlovelace** [comment]
This is a simple solution used in `cyclestreets`: 

```
  if(is.null(pat)) pat = Sys.getenv("CYCLESTREETS")
```

Source: https://github.com/Robinlovelace/cyclestreets/blob/master/R/journey.R#L71

**Comment by mem48** [comment]
Closing until a testible service exists
