### ISSUE TITLE
isochones are returning invalid geometries

### ISSUE THREAD

**Issue by mem48** [ropensci/opentripplanner#47]

**Comment by mem48** [comment]
```
isochrone = otp_isochrone(otpcon, fromPlace = c(-1.558655, 53.807870), 
                          mode = c("WALK","TRANSIT"),
                          maxWalkDistance = 3000)
```

**Comment by marcusyoung** [comment]
@mem48  haha, you found that too! I'm running sf::st_make_valid() before returning them now. Seems to work ok.

**Comment by mem48** [comment]
I'm using the st_buffer(0) trick which works and doesn't add extra dependencies. But st_make_valid should produce a similar result.
