### ISSUE TITLE
Speed up otp_plan function

### ISSUE THREAD

**Issue by Johnspeanut** [ropensci/opentripplanner#50]
Hello. 

I run otp_plan function with batch routing and multiple cores. But the takes me more than 100 hours to run the function since I try to calculate a travel time matrix of 110,000 columns and 110,000 rows. Is there any way I can speed up the otp_plan function? For example, trying to run otp_plan in C++ language? 

Thanks. 
Best,
John

**Comment by mem48** [comment]
Hi John,

12 billion routes is a lot! The switch to C wouldn't really help, as the R code spends time waiting for the Java code. So any improvement in the R code would be trivial. I do have some plans to improve the load balancing, which might see a small performance boost. You might also look at compiling the dev version of OTP 2.0 from source, as they are working on performance improvements.

If you tell me a bit more about what your trying to do I could give some extra pointers.  For example you can half your processing time if you assume travel time from A to B is the same as B to A.

**Comment by Robinlovelace** [comment]
I suggest thinking about ways to optimise your work by identifying which of the 12 billion routes are most important, e.g. which are most likely to be used and which are within a reasonable distance. In-progress function `od_create(p = your_points, max_distance = 10000)` should be able to subset only the OD pairs that are 10 KM or less apart, for example: https://github.com/ITSLeeds/od/issues/7

**Comment by Johnspeanut** [comment]
> Hi John,
> 
> 12 billion routes is a lot! The switch to C wouldn't really help, as the R code spends time waiting for the Java code. So any improvement in the R code would be trivial. I do have some plans to improve the load balancing, which might see a small performance boost. You might also look at compiling the dev version of OTP 2.0 from source, as they are working on performance improvements.
> 
> If you tell me a bit more about what your trying to do I could give some extra pointers. For example you can half your processing time if you assume travel time from A to B is the same as B to A.

Thanks a Malcolm. 

May I know where I can download OTP 2.0? I cannot find a source to download OTP2.0. 

Yes. Assuming travel time from A to B is the same as B to A is reasonable in my case. Please take a look at the code I am running.  I am trying to create a travel time OD matrix for blocks in the Washington metropolitan area. 

toPlace   = blockpoints[rep(seq(1, nrow(blockpoints)), times = nrow(blockpoints)),]
fromPlace = lblockpoints[rep(seq(1, nrow(blockpoints)), each  = nrow(blockpoints)),]

routes <- otp_plan(otpcon = otpcon,
                   fromPlace = fromPlace,
                   toPlace = toPlace,
                   fromID = fromPlace$ID,
                   toID = toPlace$ID,
                   numItineraries=1,
                   mode='TRANSIT',
                   get_geometry = FALSE,ncores=18)


Thank again for your help.

**Comment by Johnspeanut** [comment]
> I suggest thinking about ways to optimise your work by identifying which of the 12 billion routes are most important, e.g. which are most likely to be used and which are within a reasonable distance. In-progress function `od_create(p = your_points, max_distance = 10000)` should be able to subset only the OD pairs that are 10 KM or less apart, for example: [ITSLeeds/od#7](https://github.com/ITSLeeds/od/issues/7)

Thanks Robin. 
This is a good idea. 
But if I subset only OD pairs that are 10 KM or less apart, the number of points of 'from_place' is not the same as the number of points of 'to_place'. I mean if the OD matrix is not a square matrix or not a column or not a row, The batch routing version of 'otp_plan' would report errors.

**Comment by mem48** [comment]
I've not built OTP from souce myself but there are instructions at http://docs.opentripplanner.org/en/latest/Getting-OTP/#building-from-source 

If you want to do an OD matrix at block level, you could consider clustering blocks together. For example, even grouping the nearest 10 blocks into a groups would reduce the number of routes by a factor of 100. So you could get and OD matrix in just 1 hour with an accuracy of +/- a few minutes.

**Comment by mem48** [comment]
I'm going to close this issue as there is nothing wrong with the package, you just want to generate a lot of routes. 

An interesting sidenote is that you can also do this with the Google distance matrix API, and they would only charge $48 million for it.

https://developers.google.com/maps/documentation/distance-matrix/usage-and-billing

**Comment by Johnspeanut** [comment]
> I've not built OTP from souce myself but there are instructions at http://docs.opentripplanner.org/en/latest/Getting-OTP/#building-from-source
> 
> If you want to do an OD matrix at block level, you could consider clustering blocks together. For example, even grouping the nearest 10 blocks into a groups would reduce the number of routes by a factor of 100. So you could get and OD matrix in just 1 hour with an accuracy of +/- a few minutes.

This is a good idea. I will try this method. Thanks a lot.

**Comment by Johnspeanut** [comment]
> I'm going to close this issue as there is nothing wrong with the package, you just want to generate a lot of routes.
> 
> An interesting sidenote is that you can also do this with the Google distance matrix API, and they would only charge $48 million for it.
> 
> https://developers.google.com/maps/documentation/distance-matrix/usage-and-billing

Thanks.
