### ISSUE TITLE
Bug when working in non-UK time zones

### ISSUE THREAD

**Issue by mem48** [ropensci/opentripplanner#54]

**Comment by mem48** [comment]
In a nutshell, I’m located in Montreal, Quebec, where Eastern Standard Time was in effect for my date of interest (5 Feb. 2020) (GMT minus 5 hours).  For my routing, I provided  departure times with a POSIXct ymd hms format (e.g. 2013-11-21 11:30:00) and a time zone I assigned using “tz” (tz(merged_complete$parsed_time_mtl) <- "EST").  

I constructed a loop to iterate over the O-D pairs and their associated departure times (since they’re all different and I wasn’t quite sure of the best way to use one of the apply functions).  The outputs are stored in a list object that I created to hold the dataframes before binding them. 

The routing worked perfectly, but the start times in the output appear to be exactly five hours later than the inputs. For example, if I have an observation for an individual departing home at 11:30 on Feb. 5, 2020, the output sf/dataframe file has a start-time value of 16:30. I checked the time zone for the startTime and endTime columns and discovered that they’re set to GMT.  

The question I’ve got is whether the routes and travel times were actually calculated based on GMT or if the correct local time was used to determine the route and travel time. Basically, for the person who departed at 11:30 local time, did OTP consult the correct service schedule for that time (and the output merely displays the time adjusted for GMT) or did I somehow mistakenly end up looking at rush-hour bus service for 16:30?  If the departure time is wrong, do I need to subtract five hours from each departure?

I’m going to continue looking through the OTP documentation but if you have any insight, I’d really appreciate it.

**Comment by mem48** [comment]
I've pushed a commit that switches the time from GMT to UTC as this is simply wrong.

Idealy you would like the resutls back in the correct timezone. this needs some thinking about

**Comment by mem48** [comment]
The problem is not in the sending of the reqest to OTP but how the result is returned.

OTP gives time as UNIX time in milliseconds. This is correct regardelss of timezone. But the CRAN package is assuming you want the result in GMT. Which is dumb, so I've updated the github version to assume UTC which is a little better.

Idealy you would assume the correct local time, but I'm not sure if OTP returns the local timezone. This will need some thought.

**Comment by mem48** [comment]
I've just pushed another change that adds a `timezone` argument to `otp_plan` which should let you set the timezone to use. By default it will use your local timezone `Sys.timezone()` but you can also set it to any other valid timezone.

**Comment by Robinlovelace** [comment]
Awesome work, impressive quick fix :tada:

**Comment by mem48** [comment]
@Robinlovelace one to add to the list of things we need to spport in all routing packages

**Comment by mem48** [comment]
It might be useful to specify this as a global variaible e.g. via `otp_connect`

**Comment by mem48** [comment]
Note to self, demo data may not work now in non-UK regions due to wrong timezone, update examples.

**Comment by marcusyoung** [comment]
@mem48 I added tz support in otpr via otp_connect(), if you want to look at my approach. Explained in [news](https://github.com/marcusyoung/otpr/blob/master/NEWS.md) for 0.3 release.

**Comment by mem48** [comment]
Thanks, I saw your also adding support for OTP 2, looks good

**Comment by marcusyoung** [comment]
Yeah, mainly developing based on requests from one or two of our PhD students who are using it.

**Comment by mem48** [comment]
added timezone support to otp_connect, otp_plan and opt_isochrone
