### ISSUE TITLE
Any way to recover routes after R crashes?

### ISSUE THREAD

**Issue by jamiedeweese** [ropensci/opentripplanner#56]
I was trying to calculate a transit travel-time matrix for use in an accessibility analysis. I have 970 centroids, so I'm generating ~944K routes.  Just as I reached 100%--2 days and 7 hours of processing--R encountered an error.  OTPmain is still showing up in the activity monitor, with about 14.11 GB  of memory.  I'm wondering if there is any way to recover those routes before I stop the instance and try to start again.

**Comment by jamiedeweese** [comment]
I've experienced the same crash after subsetting my O-D pairs into smaller groups. I assumed that perhaps the size of the desired data frame at the end (with observations for all of the intermediate transit steps) was to blame for the crash.  My first run was 350k pairs.  The operation ran in a little over five hours on a 8-core MacBook Pro with 64 gb of memory, which seemed pretty fast.  But once I hit 100 percent, the R session aborted again.  I had previously tested with 100 points (10,000 pairs) and generated a result with no error.  I kept a close eye on the activity monitor and I still had a comfortable amount of unused memory.   Does anyone have any idea why it might be crashing R and how I can gather info on the session when the the session itself crashes? I'd like to be able to debug. 

To work around the parallel bug with Macs, I used the following work-around:

```

if (Sys.getenv("RSTUDIO") == "1" && !nzchar(Sys.getenv("RSTUDIO_TERM")) && 
    Sys.info()["sysname"] == "Darwin" && getRversion() == "4.0.0") {
  parallel:::setDefaultClusterOptions(setup_strategy = "sequential")
}

**This is the script I was using:**
## this is necesssary to fix a problem with the update to R 4.0.  Also loaded in user home profile
# R.home()
# file.edit(file.path("~", ".Rprofile"))
library(parallel)
if (Sys.getenv("RSTUDIO") == "1" && !nzchar(Sys.getenv("RSTUDIO_TERM")) && 
    Sys.info()["sysname"] == "Darwin" && getRversion() == "4.0.0") {
  parallel:::setDefaultClusterOptions(setup_strategy = "sequential")
}

setwd("~/OneDrive/Documents/MUP_McGill/TRAM/9-RouteRidership")

library(cancensus)
library(tidyverse)
library(opentripplanner)
library(tidyr)
library(dplyr)
library(lubridate)
library(sf)

cents_2016_snapped <- st_read("centroids_2016_snapped.gpkg")

## download OSM .pbf file for use in construction graph

# download full Quebec pbf from Geofabrik and then use command-line osmconverter utility to trim to appropriate area

## construct graph for 2012

# this is where all of the data is kept; see vignette for proper folder structure/contents
path_data <- file.path("/Users/jamesdeweese/Documents/R_work/OTP")

# this is where the the OTP program is kept
path_otp <- c("/Users/jamesdeweese/Documents/R_work/OTP/otp.jar")

#builds the graph; don't run again after built if graph.obj is saved (router is the folder name)
log1 <- otp_build_graph(otp = "/Users/jamesdeweese/Documents/R_work/OTP/otp.jar" , dir = path_data, memory = 30240, router="montreal_nov_2012")

## configure the router

router_config <- otp_make_config("router")     # Make a config object
router_config$routingDefaults$maxWalkDistance <- 2000      # set max walk to 2 km
otp_validate_config(router_config)             # Check the new config is valid
otp_write_config(router_config,                # Save the config file
                 dir = path_data,
                 router = "montreal_nov_2012")

# open up router
log2 <- otp_setup(otp = path_otp, dir = path_data, port = 8801, securePort = 8802, router = "montreal_nov_2012", memory = 30240)

# verify routes loaded

library(jsonlite)
check_routes <- fromJSON("http://localhost:8801/otp/routers/montreal_nov_2012/index/routes")

# connect R and localhost

otpcon <- otp_connect(hostname =  "localhost",
                      router = "montreal_nov_2012",
                      port = 8801)
## create TT matrix
cents_2016_snapped <- arrange(cents_2016_snapped,GeoUID)
#cents <- sample_n(cents_2016_snapped, 100)
cents <- cents_2016_snapped %>% select(GeoUID)

to   = cents[rep(seq(1, nrow(cents)), times = nrow(cents)),]
from = cents[rep(seq(1, nrow(cents)), each  = nrow(cents)),]
dep_date <- ISOdate(2012,11,13,08,00,00,tz="EST")

### split up to and from into more manageable chunk

to1 <- slice(to, 1:350000)
to2 <- slice(to,350001:700000)
to3 <- slice(to, 700001:938961)

from1 <- slice(from, 1:350000)
from2 <- slice(from,350001:700000)
from3 <- slice(from, 700001:938961)

# must convert back to lon,lat for otp plan.  Won't accept projections.  Should update this in the vignette

to <- st_transform(to, crs = 4326)
from <- st_transform(from, crs = 4326)

routes <- otp_plan(otpcon = otpcon,
                   fromPlace = from1,
                   toPlace = to1,
                   fromID = from1$GeoUID,
                   toID = to1$GeoUID,
                   date_time = dep_date,
                   get_geometry = FALSE,
                   numItineraries = 1,
                   mode = c("WALK", "TRANSIT"),
                   ncores = 7)



**System info:**

MacBook Pro, macOS Catalina Version 10.15.4
2.3 GHz 8-core I9
64 GB

R version 4.0.0 (2020-04-24) -- "Arbor Day"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin17.0 (64-bit)

RStudio
Version 1.2.5042

```

**Comment by mem48** [comment]
I edited your comment to add ``` code blocks, to make it easier to read

**Comment by mem48** [comment]
You are doing very large batches which suggest that it could be a memory problem. Especially as you said, it worked fine with small batches. I've successfully run up to 1 million routes at once, but on a 128GB workstation. 

As it is failing once you reach 100% the problem probably comes from joining the results together from each of the workers. You are using `ncores = 7` so you have 7 * 50,000 row dataframes in memory and then R will try to bind them together into 1 350,000 row dataframe. This is done with `dplyr::bind_rows()` and so would briefly double the memory use of R. I expect this is when the crash occurs.

**Comment by mem48** [comment]
If batches of 10,000 work, write a simple loop to work over your whole dataset in batches. You can save each batch to disk and prevent and progress being lost. Apart from the time writing to disk, there will be no significant slow down in computation time.
Also after generating each batch, you could drop any columns you don't need which would free up memory. 

And to answer your original question, no there is no way to recover the data after a crash.

**Comment by mem48** [comment]
@jamiedeweese I'm closing this unless you have any other questions, I've added a new `distance_balance` argument to `otp_plan` in the dev version, it should offer a small performance boost (about 5%) at the expense of the routes coming back in a different order to they are requested. It is a small gain, but when you're running such large batches it would be worth having.
