### ISSUE TITLE
small typo in vignette

### ISSUE THREAD

**Issue by jamiedeweese** [ropensci/opentripplanner#57]
While teaching myself using the vignettes, I came across a smaller error in the advanced vignette. (https://cran.r-project.org/web/packages/opentripplanner/vignettes/advanced_features.html) 

In the pivot_wider function, the document uses the older terminology from the spread and gather functions (key and value) instead of names_to and values_to.  It throws an error when executing the code.

routes <- otp_plan(otpcon = otpcon,
                   fromPlace = fromPlace,
                   toPlace = toPlace,
                   fromID = fromPlace$geo_code,
                   toID = toPlace$geo_code,
                   get_geometry = FALSE)
routes <- routes[,c("fromPlace","toPlace","duration")]
# Use the tidyr package to go from long to wide format
routes_matrix <- tidyr::pivot_wider(routes, 
                               key = "toPlace", 
                               value = "duration")

**Comment by mem48** [comment]
Thanks, I've updated the vignette
