### ISSUE TITLE
otp_plan fails with error: found multiple dimensions: XYZ XY

### ISSUE THREAD

**Issue by mem48** [ropensci/opentripplanner#60]
This is a known error with sf and dplyr 1.0

https://github.com/r-spatial/sf/issues/1390

Current workarounds

revert to dplyr 0.8.5

Use otp without a DEM, as problem is only with XYZ coordinates

**Comment by Robinlovelace** [comment]
Have you tried `data.table`? I found `rbindlist()` more than 100 times faster than `rbind()` and much faster than `bind_rows()`.

**Comment by mem48** [comment]
I'd have to rewrite a big chunk of the package

**Comment by Robinlovelace** [comment]
> I'd have to rewrite a big chunk of the package

I don't think so. It's not necessarily an either/or. I recently added `data.table` as a Suggests to `stplanr` just for the fast row binding functionality. If it's a Suggests it doesn't increase install times be default.

**Comment by mem48** [comment]
I gave it a go, but now tha package needs both dplyr and data.table. Is there an alterative to bind_cols?

**Comment by Robinlovelace** [comment]
`cbind()` is pretty fast, not a bottleneck in the same way `rbind()` can be I think. Not sure if there's a `data.table` equivalent but would be surprised if not.

**Comment by mem48** [comment]
Github version is now using dev versions of `sf` and `vctrs` until this is fixed

**Comment by mem48** [comment]
Fixed and sent to CRAN, still problem with no binary for `vctrs 0.3.1` so now working on `data.table`
