### ISSUE TITLE
R OTP initialization not working 

### ISSUE THREAD

**Issue by lgaa320** [ropensci/opentripplanner#62]
Hello!

I'm attempting to use OTP in R. I downloaded Java 8u251, and have been following the setup steps outlined in the getting started vignette. My commands entered thusfar are:

```
path_data <- file.path(tempdir(), "OTP")
dir.create(path_data) 
path_otp <- otp_dl_jar(path_data)
otp_dl_demo(path_data)
log1 <- otp_build_graph(otp = path_otp, dir = path_data) 
```
However, upon entering the log1 command, I receive the following error message:
```
2020-06-12 18:57:33 Basic checks completed, building graph, this may take a few minutes
The graph will be saved to []AppData\Local\Temp\RtmpasiS8P/OTP
2020-06-12 18:57:34 Failed to build graph with message:
Error occurred during initialization of VMCould not reserve enough space for 2097152KB object heap
Warning message:
In system(text, intern = TRUE) :
  running command 'java -Xmx2048M -jar "[]AppData\Local\Temp\RtmpasiS8P/OTP/otp.jar" --build "[]AppData\Local\Temp\RtmpasiS8P/OTP/graphs/default"' had status 1
```
I attempted setting memory to 5000 and 2500 -- did not solve the issue. How should I proceed?

Thanks much.

**Comment by mem48** [comment]
Java is asking for an additional 2,097,152 KB of memory, so `memory = 2500` should work.

What error message do you get then? How much RAM do you have in total? Do you have 32 Bit or 64 Bit Java installed?

**Comment by lgaa320** [comment]
Was checking my Java in trying to respond to your question...figured it out! I had accidentally installed 32 bit Java on my 64 bit computer. All is working now. Thanks for your help.
