### ISSUE TITLE
maxTransfers is logical in otp_validate_routing_options when it should be integer

### ISSUE THREAD

**Issue by rafavdz** [ropensci/opentripplanner#69]
Hi, 

Great package I am enjoying it a lot! Thanks for the contribution.

I tried to edit  otp_routing_options to limit the number of transfers in a request. However, when using otp_validate_routing_options it fails since it expecting a logical value when it should be an integer.

```
 routingOptions <- otp_routing_options()
 routingOptions$maxTransfers <- 3
 routingOptions <- otp_validate_routing_options(routingOptions)
```

Returns:

```
Error in otp_validate_routing_options(routingOptions) : 
  Assertion on 'opts$maxTransfers' failed: Must be of type 'logical' (or 'NULL'), not 'double'.
```

Best,
Rafa

**Comment by mem48** [comment]
Thanks, @rafavdz I've just committed a fix to a branch that I'm working on. So will come to the CRAN package eventually. In the meantime, you could manually edit the config JSON to add the maxTransfers value you want.

**Comment by jc-ulles** [comment]
Hi, I have exactly the same problem with version 0.5.1. I solved the problem by defining:
```
router_config <- otp_make_config(type = "router")  
router_config$routingDefaults$maxTransfers <- as.integer(1)
```
