### ISSUE TITLE
Write tests

### ISSUE THREAD

**Issue by mem48** [ropensci/opentripplanner#7]

**Comment by layik** [comment]
yes :)

**Comment by layik** [comment]
#8

**Comment by layik** [comment]
Awesome tests @mem48. Given more time, appveyor could be ideal to make the test coverage 100%
It comes with JDK (Java Development Kit) which means we could download, setup and run OTP.

https://www.appveyor.com/docs/windows-images-software/#java

Maybe someone can do it in future :)
