### ISSUE TITLE
0.3 release

### ISSUE THREAD

**Issue by mem48** [ropensci/opentripplanner#73]
- [x] route option missing from results

- [x] benchmark results

- [x] check otp_plan for all modes

- [x] check otp_isochrone

- [x] run full tests

- [x] increase code coverage

- [x] run onboarding tests

- [ ] spell check documentation

**Comment by mem48** [comment]
- [x] elevation always returned

**Comment by mem48** [comment]
- [x] incorrect bbox from otp_plan

**Comment by mem48** [comment]
- [x] improve test quality

**Comment by mem48** [comment]
- [x] transit routing  Error in data.table::rbindlist(results_routes) : 
  Item 2 has 34 columns, inconsistent with item 1 which has 43 columns. To fill missing columns use fill=TRUE.

**Comment by mem48** [comment]
- [x] Fare missing for transit routes

**Comment by Robinlovelace** [comment]
Great to see all these issues resolved. Let me know if you'd like me to test any of the new functionality.
