### ISSUE TITLE
Add code coverage and AppVeyor

### ISSUE THREAD

**Issue by mem48** [ropensci/opentripplanner#8]
@Robinlovelace @layik, please advise

**Comment by layik** [comment]
accepted :)

**Comment by layik** [comment]
I just need https://codecov.io/gh/ITSLeeds/opentripplanner setup. I could do it on my personal account but much better be done by @Robinlovelace who I "think" has that account.

**Comment by layik** [comment]
Doing it.

**Comment by layik** [comment]
https://github.com/ITSLeeds/opentripplanner/commit/1ec71193a6e642f7596ee7020d426240efbebd0f

That is done, because we run everything under "IHAVEOTP" it shows 0 on Travis. That is something for us to ignore/sort out as local tests would be different.

**Comment by mem48** [comment]
@layik  did you add AppVeyor or just code coverage?

**Comment by layik** [comment]
Do we need it? 
CI Travis 
Tests CodeCov

**Comment by mem48** [comment]
It's on the ropensci requirements because Travis does not build on windows, but AppVeyor does

**Comment by layik** [comment]
@mem48 I am a total beginner on AppVeyor. I hope this is right, but we do need to make sure `usethis::use_appveyor` default setup does the job. By learning more about `appveyor`. 

Since when it has become a requirement, as `stats19` did not need it.

**Comment by Robinlovelace** [comment]
I don't think it's a hard requirement. @maelle clarification welcome from an @rOpenSci perspective!

**Comment by maelle** [comment]
:wave:! I'm not familiar with what your package does, here are our criteria to require CI on all platforms https://ropensci.github.io/dev_guide/ci.html#whichci I hope it helps!

**Comment by Robinlovelace** [comment]
Thanks for the clarification @maelle.

**Comment by mem48** [comment]
@Robinlovelace my reading of the requirements was:

> R packages should have CI for all platforms when they contain:
>     Packages with system calls

requires CI on Windows, Mac and Linux, however, I'm not sure if it will help because the system calls can't be tested easily without Java and OTP. Perhaps the most we can do is test the java version?

**Comment by Robinlovelace** [comment]
We'll see what comes out in the wash during the review process. I think it may be possible to test a working instance on all 3 platforms, but may end up being more hassle than it's worth and not an efficient use of time. However, with support from rOpenSci, and the impressive level of support they provide, anything is possible (they helped me get travis set-up with stplanr before I even knew what that was, many thanks to @karthik https://github.com/ropensci/stplanr/commits?author=karthik ).

**Comment by layik** [comment]
I think it will be an overkill to set up an instance and I almost had a go at it last night. 

We could use an open API for the tests. Clarification means it is not a strict requirement. It would be if our package was say Windows only. 

CRAN requires at least two OS’s “tested”.

**Comment by layik** [comment]
I am satisfied this is enough and as Robin says let’s get the reviews.

**Comment by Robinlovelace** [comment]
> We could use an open API for the tests.

Thats a good idea and @itsleeds should have its own server.

**Comment by mem48** [comment]
How would we get one set up?

**Comment by layik** [comment]
One of these:
http://docs.opentripplanner.org/en/latest/Deployments/

This?
http://docs.plannerstack.org/en/latest/

**Comment by mem48** [comment]
@layik great find of plannerstack I've been looking for one with a free public api for ages
