### ISSUE TITLE
N*N matriz 

### ISSUE THREAD

**Issue by orlandombaa** [ropensci/opentripplanner#80]
Hello 

I just created a  GTFS for an alternative transit network for a project. I want to generate a N*N matrix from all my origins to all my destinations. 
I am trying to this with two different approaches. One is the following: 

1) 
`toPlace <- centroides [rep(seq(1,nrow(centroides)), times= nrow(centroides)),]`
`fromplace <- centroides [rep(seq(1,nrow(centroides)), each= nrow(centroides)),]`

`#########      MATRIZ  N*N      ############`
`OD_Matriz <- otp_plan(otpcon = otpcon, fromPlace = fromplace, toPlace = toPlace,`
 `                    mode= c("WALK","TRANSIT"), ncores = 5, get_geometry = FALSE, `
  `                    numItineraries = 1) `

2) the second approach is that I have the coordinates of my centroids into a SF class object and using the next code: 

`#########      MATRIZ  N*N      ############`
`OD_Matriz <- otp_plan(otpcon = otpcon, fromPlace = centroids, toPlace = centroids,`
 `                    mode= c("WALK","TRANSIT"), ncores = 5, get_geometry = FALSE, `
  `                    numItineraries = 1) `

However, both give me an error with the following message: 

`Error in otp_plan(otpcon = otpcon, fromPlace = fromplace, toPlace = toPlace,  : `
 ` The length of fromID and fromPlace are not the same`

I used to have an old cold for generating a N*N matrix and this error did not appear. I have read the information about fromID and toID  and I don't know very well what these arguments mean.

**Comment by mem48** [comment]
You are inputing `fromID = c("WALK","TRANSIT")` I think you mean `mode = c("WALK","TRANSIT")`

**Comment by orlandombaa** [comment]
Hello 

Sorry, yes it is `mode =  c("WALK","TRANSIT")` it was a mistake when I write her but in the code I have that. I attach a photo:



https://mega.nz/file/KRxAyR6D#_5S-lm2vSo4kepdz2T-zmsf38V7BfzDrMb7MkBeCt7k

**Comment by mem48** [comment]
That doesn't give me but to go on, but the error message is clear `The length of fromID and fromPlace are not the same` you can check this with `length(fromPlace) == length(fromID)`

**Comment by mem48** [comment]
Also you seem to be using the same object for fromID and toID which will not work. Look at the example in the documentation https://docs.ropensci.org/opentripplanner/articles/advanced_features.html#all-to-all-routing

**Comment by orlandombaa** [comment]
Thank you. I read the documentation and it worked!

**Comment by mem48** [comment]
A valuable life lesson 😆
