### ISSUE TITLE
[BUG] Datetime being parsed incorrectly

### ISSUE THREAD

**Issue by dhersz** [ropensci/opentripplanner#85]
**Describe the bug**
I'm trying to calculate some routes departing from the following datetime: `format(as.POSIXct("13-05-2019 14:00:00", format = "%d-%m-%Y %H:%M:%S"`. However, `otp_plan()` only returns itineraries that start very early in the morning. I tried playing a bit with the `timezone` argument but nothing worked. Then I checked how datetimes were parsed inside the function and realized that "14:00:00" is being parsed as "02:00", without am/pm indicator.

**To Reproduce**
```r
date_time <- as.POSIXct("13-05-2019 14:00:00", format = "%d-%m-%Y %H:%M:%S")
timezone <- "America/Sao_Paulo"

date <- format(date_time, "%m-%d-%Y", tz = timezone)
time <- tolower(format(date_time, "%I:%M%p", tz = timezone))

date
#> [1] "05-13-2019"
time
#> [1] "02:00"
```

**Expected behavior**
`time` should be `02:00pm`

**System**
```r
R version 4.0.4 (2021-02-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.2 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=pt_BR.UTF-8       LC_NUMERIC=C               LC_TIME=pt_BR.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=pt_BR.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=pt_BR.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=pt_BR.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.13.6     opentripplanner_0.3.1

loaded via a namespace (and not attached):
 [1] rstudioapi_0.13   knitr_1.31        magrittr_2.0.1    R6_2.5.0         
 [5] rlang_0.4.10      pbapply_1.4-3     highr_0.8         tools_4.0.4      
 [9] parallel_4.0.4    geodist_0.0.7     checkmate_2.0.0   xfun_0.21        
[13] tinytex_0.29      cli_2.3.0         clipr_0.7.1       htmltools_0.5.1.1
[17] ellipsis_0.3.1    yaml_2.2.1        digest_0.6.27     assertthat_0.2.1 
[21] tibble_3.0.6      lifecycle_1.0.0   crayon_1.4.1      processx_3.4.5   
[25] callr_3.5.1       ps_1.5.0          vctrs_0.3.6       fs_1.5.0         
[29] curl_4.3          glue_1.4.2        evaluate_0.14     rmarkdown_2.6    
[33] reprex_1.0.0      compiler_4.0.4    pillar_1.4.7      backports_1.2.1  
[37] pkgconfig_2.0.3  
```

**Comment by mem48** [comment]
@dhersz can you share the code you are using for `opentripplanner` otherwise I can't see what you are doing

**Comment by mem48** [comment]
Also I suggest you use the `lubridate` package as formatting date-times in R can be fiddly

```
date_time = lubridate::dmy_hms("13-05-2019 14:00:00", tz = "America/Sao_Paulo")
tolower(format(date_time, "%I:%M%p", tz = "America/Sao_Paulo"))
[1] "02:00pm"

```

**Comment by dhersz** [comment]
This is how I'm calling `otp_plan()`:

```r
  routes <- otp_plan(
    otpcon, 
    from_place, 
    to_place, 
    fromID = from_place_ids, 
    toID = to_place_ids,
    mode = c("WALK", "TRANSIT"),
    date_time = as.POSIXct("13-05-2019 14:00:00", format = "%d-%m-%Y %H:%M:%S"),
    maxWalkDistance = 1000,
    numItineraries = 1,
    ncores = n_cores,
    distance_balance = TRUE,
    get_geometry = FALSE
  )
```

**EDIT:**

I think this has to do with my OS, I just tried with `lubridate` and I get the same results.

**Comment by mem48** [comment]
Did you specify a `timezone` in `otpcon` and have you tried using lubridate. I think the problem is with how you are specifying the `date_time`

**Comment by mem48** [comment]
Doesn't sound like a problem with the package, as I can get the correct time on my computer. I'd try googling date/time problems in R

**Comment by dhersz** [comment]
Yes, `otpcon$timezone` is specified as `"America/Sao Paulo"`.

Also tried with `lubridate` and didn't work. The problem might be with my OS? Not sure.

```r
date_time <- lubridate::dmy_hms("13-05-2019 14:00:00", tz = "America/Sao_Paulo")

date <- format(date_time, "%m-%d-%Y", tz = "America/Sao_Paulo")
time <- tolower(format(date_time, "%I:%M%p", tz = "America/Sao_Paulo"))

date
#> [1] "05-13-2019"
time
#> [1] "02:00"
```

**Comment by dhersz** [comment]
From `strftime()` documentation:

> %p
> AM/PM indicator in the locale. Used in conjunction with %I and not with %H. **An empty string in some locales** (for example on some OSes, non-English European locales including Russia). The behaviour is undefined if used for input in such a locale.

**Comment by mem48** [comment]
Perhaps your local does not support the `%p` ? OpenTripPlanner expects the time with an AM/PM value. Could you change your local in R. I think Greenland shares a timezone with Brazil?

**Comment by dhersz** [comment]
Changing system locale did the trick!

```r
Sys.setlocale("LC_TIME","en_US.UTF-8")
#> [1] "en_US.UTF-8"

date_time <- as.POSIXct("13-05-2019 14:00:00", format = "%d-%m-%Y %H:%M:%S")
timezone <- "America/Sao_Paulo"

time <- tolower(format(date_time, "%I:%M%p", tz = timezone))
time
#> [1] "02:00pm"
```

Thanks for the heads-up @mem48!
