### ISSUE TITLE
Codecov sec breach

### ISSUE THREAD

**Issue by layik** [ropensci/opentripplanner#88]
The issue template is strict so apologies. It's worth checking credentials in codecov. 

https://about.codecov.io/security-update

**Comment by mem48** [comment]
Thanks @layik, sound like we should be doing this for all our packages

**Comment by layik** [comment]
According to `covr` author (Jim) https://twitter.com/jimhester_/status/1382692471612833796, we should be good. When it comes to security, though, I am terribly cynical. But if rOpenSci are happy, I would be happy, too. I will close the ticket but anyone with better judgement can reopen it.
