### ISSUE TITLE
write JOSS paper

### ISSUE THREAD

**Issue by mem48** [ropensci/opentripplanner#9]

**Comment by mem48** [comment]
First draft https://github.com/ITSLeeds/opentripplanner/blob/master/paper.md

Would welcome comments from @marcusyoung @Robinlovelace @layik

**Comment by mem48** [comment]
See https://joss.readthedocs.io/en/latest/submitting.html for guidelines

**Comment by Robinlovelace** [comment]
Heads-up @mem48 I'm working on this now.
