### ISSUE TITLE
Error in otp_clean_input(fromPlace, "fromPlace") :    fromPlace contains non-POINT geometry

### ISSUE THREAD

**Issue by orlandombaa** [ropensci/opentripplanner#91]
Hello 

I am trying to generate a matriz N*N.   The steps that I am following is the next: 

- I read my centroides (the file is shapefile) as SF. 
- I generate my set of origin an destination using the following code: 

`toPlace_1   = centroides_1[rep(seq(1, nrow(centroides_1)), times = nrow(centroides_1)),]
fromPlace_1 = centroides_1[rep(seq(1, nrow(centroides_1)), each  = nrow(centroides_1)),]` 

- I request the generation of the matrix: 
`routes_1_1 <- otp_plan(otpcon = otpcon,
                   fromPlace = fromPlace_1,
                   toPlace = toPlace_1,
                   fromID = fromPlace_1$ID,
                   toID = toPlace_1$ID,
                   get_geometry = FALSE,
                   mode = c("WALK","TRANSIT"),
                   ncores = 5, numItineraries = 1,
                   maxWalkDistance = 1500)`

However I got the following error: 

"Error in otp_clean_input(fromPlace, "fromPlace") : 
  fromPlace contains non-POINT geometry"

I dont know what is the problem I used the same code for run another N*N matriz without problems. I hope someone can help me.

Thank you

**Comment by mem48** [comment]
"fromPlace contains non-POINT geometry"

try plotting your fromPlace at least some of them are not points

**Comment by orlandombaa** [comment]
Hello @mem48 

Thank you for your answer.  I dont think that that´s the reason. The centroids the I read previous to create te DF "FromPlace" it is completly points. This is the DF of "FromPlace": 

![R](https://user-images.githubusercontent.com/48104481/118344172-8ddba700-b4f2-11eb-8850-8d7d112f941a.PNG)




The file that I read as centroids is a shape file that I create generating centroids from a polygon layer.

**Comment by mem48** [comment]
This is the check

https://github.com/ropensci/opentripplanner/blob/2af4df35f792772e5e4d4b82ac16220d4d7dd45f/R/otp-plan.R#L409

There must be missing or erroneous data.

**Comment by mem48** [comment]
Try running

summary(st_geometry_type(fromPlace))

**Comment by orlandombaa** [comment]
Hello @mem48 

Thank you, your answer give me the path to solve it. It turns that even that the original shape file was totally  made by points it was saved as "Multi points"  you can see it here: 

![multipoints](https://user-images.githubusercontent.com/48104481/118364569-936ed680-b55e-11eb-9783-b09b6401f82e.PNG)



I convert it to points with the function "convert  multipoints to points" in Qgis: 


![points](https://user-images.githubusercontent.com/48104481/118364604-b5685900-b55e-11eb-9209-76afd3f51a82.PNG)



With that the problem was solved. 

Thank you !
