### ISSUE TITLE
Matrix, columns names from fromID and row names from toID

### ISSUE THREAD

**Issue by orlandombaa** [ropensci/opentripplanner#94]
Hello 

I am trying to generate a N*N travel time matrix where the name and rows of the columns indicate de ID of the origin and destination.  Reading the following documentation https://docs.ropensci.org/opentripplanner/articles/Analyst.html     

I see that I need the version 1.5 of  OTP  which I already download and activate the analyst feature in the setup process. However, the opentriplanner package does not have the function of  `otp_traveltime` in the version 0.2.3 and 0.3.1.

Is there any other way to generate this matrix? 

Best regards, 
Orlando

**Comment by mem48** [comment]
You need to install the github bersion of the package at otp_traveltime is still experimental.

Use

remotes::install_github("ropensci/opentripplanner")

**Comment by orlandombaa** [comment]
Thank you! I will try with this version  @mem48
